### ISSUE TITLE
Clean up pallets.ipynb , validate simple model works and output a valid looking 'punk'

### ISSUE THREAD

**Issue by tnn1t1s** [jmsdnns/pallets#1]
Clean up pallets.ipynb , validate simple model works and output a valid looking 'punk' by creating a random array in the latent spcae and visualizing it use `plt`

**Comment by jmsdnns** [comment]
This is complete!

A picture is shown at the bottom of the section called _Model Output to Image_ in this notebook https://github.com/tnn1t1s/pallets/blob/444bb8be5859d19d84db5577ae9acb3d0607ba7c/nb/pallets.ipynb
