### ISSUE TITLE
add a score function and score the OneHotAutoEncoder

### ISSUE THREAD

**Issue by tnn1t1s** [jmsdnns/pallets#2]
add a score function and score the OneHotAutoEncoder

**Comment by jmsdnns** [comment]
Complete!

Scoring is done for all 4 models, including the two one hot encoded models: `NaiveOneHotAutoencoder` and `ConvOneHotEncoded`.

The scoring is done during training and testing, visible in the training loop here: https://github.com/tnn1t1s/pallets/blob/444bb8be5859d19d84db5577ae9acb3d0607ba7c/pallets/models.py#L120

Can see the score values from training and testing, along with a graph of its performance at the bottom of this notebook: https://github.com/tnn1t1s/pallets/blob/444bb8be5859d19d84db5577ae9acb3d0607ba7c/nb/pallets.ipynb
