### ISSUE TITLE
Debug SimpleConvAutoencoder(nn.Module)

### ISSUE THREAD

**Issue by tnn1t1s** [jmsdnns/pallets#3]
while this technically works - the training score is high but the output images do not look anything like valid punks. there's something wrong here that needs to be debugged.

**Comment by jmsdnns** [comment]
The model that was called `SimpleConvAutoencoder` is now split into two Conv models, one based on using 4 channels for RGBA values and one based on one-hot encoding of the color palette. They both work correctly now.

Implementations:
* [ConvRGBAAutoencoder](https://github.com/tnn1t1s/pallets/blob/444bb8be5859d19d84db5577ae9acb3d0607ba7c/pallets/models.py#L67)
* [ConvOneHotAutoencoder](https://github.com/tnn1t1s/pallets/blob/444bb8be5859d19d84db5577ae9acb3d0607ba7c/pallets/models.py#L94)

An image generated with the RGBA model:
![conv-rgba](https://github.com/tnn1t1s/pallets/assets/7950614/803c617d-9054-4698-944f-8b1ccdc29bf5)

An image generated with the one hot encoded model:
![conv-onehot](https://github.com/tnn1t1s/pallets/assets/7950614/98989995-34c9-461a-84df-6b3166118330)
